site_name: Treex
repo_name: cgarciae/treex
repo_url: https://github.com/cgarciae/treex
site_url: https://cgarciae.github.io/treex
nav:
- Treex: index.md
- User Guide:
    User Guide: user-guide/intro.md
    Defining Modules: user-guide/defining-modules.md
    Initialization: user-guide/initialization.md
    Module API:
      Filter: user-guide/api/filter.md
      Merge: user-guide/api/merge.md
      Map: user-guide/api/map.md
    Optimizer: user-guide/optimizer.md
    State Management: user-guide/state-management.md
    Training State: user-guide/training-state.md
    Freezing Modules: user-guide/freezing-modules.md
- API Reference: {}
extra:
  search:
    language: en
  social:
  - icon: octicons/mark-github-16
    link: https://github.com/cgarciae
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cgarciae88
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/cgarciae
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16
markdown_extensions:
- pymdownx.arithmatex
- admonition
- pymdownx.highlight
- pymdownx.superfences
- codehilite:
    guess_lang: false
    use_pygments: true
    noclasses: true
    pygments_style: default
plugins:
- search
- mkdocs-jupyter
- mkdocstrings
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
